- name: Download Puppet release package
  get_url:
    url: https://apt.puppet.com/puppet7-release-jammy.deb
    dest: /tmp/puppet7-release-jammy.deb
    mode: '0644'

- name: Install Puppet release package
  command: dpkg -i /tmp/puppet7-release-jammy.deb
  become: yes

- name: Update APT cache
  apt:
    update_cache: yes
  become: yes

- name: Install PuppetDB
  apt:
    name: puppetdb
    state: present
  become: yes

- name: Ensure PuppetDB service is enabled and started
  systemd:
    name: puppetdb
    enabled: yes
    state: started
  become: yes

- name: Check PuppetDB status
  command: systemctl status puppetdb
  register: puppetdb_status
  ignore_errors: yes
  become: yes

- name: Debug PuppetDB status
  debug:
    var: puppetdb_status

- name: Get PuppetDB logs
  command: journalctl -xeu puppetdb.service
  register: puppetdb_logs
  ignore_errors: yes
  become: yes

- name: Debug PuppetDB logs
  debug:
    var: puppetdb_logs.stdout_lines