# roles/puppet_agent/tasks/main.yml
---
- name: Download Puppet release package
  get_url:
    url: https://apt.puppet.com/puppet7-release-jammy.deb
    dest: /tmp/puppet7-release-jammy.deb
    mode: '0644'

- name: Install Puppet release package
  command: dpkg -i /tmp/puppet7-release-jammy.deb
  become: yes

- name: Update APT cache
  apt:
    update_cache: yes
  become: yes

- name: Install Puppet Server
  apt:
    name: puppetserver
    state: present
  become: yes

- name: Ensure Puppet service is enabled and started
  systemd:
    name: puppetserver
    enabled: yes
    state: started
  become: yes

- name: Check Puppet Server status
  command: systemctl status puppetserver
  register: puppetserver_status
  ignore_errors: yes
  become: yes

- name: Debug Puppet Server status
  debug:
    var: puppetserver_status

- name: Get Puppet Server logs
  command: journalctl -xeu puppetserver.service
  register: puppetserver_logs
  ignore_errors: yes
  become: yes

- name: Debug Puppet Server logs
  debug:
    var: puppetserver_logs.stdout_lines

# - name: Configure Puppet agent
#   template:
#     src: puppet.conf.j2
#     dest: /etc/puppetlabs/puppet/puppet.conf
#   notify:
#     - Restart Puppet agent