---
- hosts: puppet_agents
  tasks:
    - name: Request certificate from Puppet CA
      command: /opt/puppetlabs/bin/puppet agent --test 
      register: puppet_cert_request
      ignore_errors: true
      become: yes

    - name: Check if certificate request was successful
      debug:
        var: puppet_cert_request.stdout
