---
- name: Configure Puppet Server and Agent on Ubuntu 22.04
  hosts: puppet_agents
  become: yes
  tasks:
    - name: Download Puppet release package
      command: wget https://apt.puppet.com/puppet7-release-jammy.deb -O /tmp/puppet7-release-jammy.deb

    - name: Install Puppet release package
      command: dpkg -i /tmp/puppet7-release-jammy.deb

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Puppet Server
      apt:
        name: puppetserver
        state: present

    - name: Ensure Puppet Server is enabled and started
      systemd:
        name: puppetserver
        enabled: yes
        state: started

    - name: Install Puppet Agent
      apt:
        name: puppet-agent
        state: present

    - name: Ensure Puppet Agent is enabled and started
      systemd:
        name: puppet
        enabled: yes
        state: started

    - name: Ensure Puppet configuration directory exists
      file:
        path: /etc/puppetlabs/puppet
        state: directory

    - name: Configure Puppet Agent
      template:
        src: puppet.conf.j2
        dest: /etc/puppetlabs/puppet/puppet.conf

    - name: Ensure Puppet Agent service is enabled and started
      systemd:
        name: puppet
        enabled: yes
        state: started
