---
- name: Configure Puppet Agent on Ubuntu 22.04
  hosts: puppet_agents
  become: yes
  tasks:
    - name: Download Puppet release package
      get_url:
        url: https://apt.puppet.com/puppet7-release-jammy.deb
        dest: /tmp/puppet7-release-jammy.deb

    - name: Install Puppet release package
      dpkg:
        name: /tmp/puppet7-release-jammy.deb
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Puppet Server
      apt:
        name: puppetserver
        state: present

    - name: Ensure Puppet Server is enabled and started
      systemd:
        name: puppetserver
        enabled: yes
        state: started
