---
- name: Configure Puppet Agent on Ubuntu 22.04
  hosts: puppet_agents
  become: yes
  tasks:
    - name: Add Puppet APT key
      apt_key:
        url: https://apt.puppet.com/DEB-GPG-KEY-puppet
        state: present
    
    - name: Add Puppet repository to sources list
      apt_repository:
        repo: 'deb http://apt.puppet.com/ubuntu jammy puppet7'
        state: present
    
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Puppet Agent
      apt:
        name: puppet-agent
        state: present

    - name: Ensure Puppet configuration directory exists
      file:
        path: /etc/puppetlabs/puppet
        state: directory

    - name: Configure Puppet Agent
      template:
        src: puppet.conf.j2
        dest: /etc/puppetlabs/puppet/puppet.conf

    - name: Enable and start Puppet Agent service
      systemd:
        name: puppet
        enabled: yes
        state: started
