---
- hosts: puppet_agents
  roles:
    - { role: puppet_agent, tags: 'puppet-agent' }
  
- hosts: puppet_server
  roles:
    - { role: puppet_server, tags: 'puppet-server' }

- hosts: puppet_db
  roles:
    - { role: puppet_db, tags: 'puppet-db' }