---
- hosts: puppet_agents
  roles:
    - puppet_agent
  
- hosts: puppet_server
  roles:
    - puppet_server

# - hosts: puppet_db
#   roles:
#     - puppet_db
  
# - hosts: puppet_server
#   tasks:
#     - name: Restart Puppet Server
#       systemd:
#         name: puppetserver
#         state: restarted
#       become: yes
